массивы NumPy могут быть обычными операндами в математических выражениях:

In [ ]:
import numpy as np

a = [1, 2, 3]    #  список Python
b = np.array([1, 2, 3])    #  массив NumPy
c = 7

In [ ]:
#  Если мы умножим список на число:
a * c

In [ ]:
#  Теперь умножим массив NumPy на число:
b * c

In [ ]:
#  Прибавим к массиву число:
b + c

Для выполнения таких операций на Python, мы были вынуждены писать циклы. 

в NumPy все операции выполняются поэлементно:

In [ ]:
a = np.array([[5, 7], [11, 13]])
a / 3 #  обычное деление

In [ ]:
a // 3 #  целочисленное деление

In [ ]:
a % 3 #  остаток от деления

In [ ]:
a ** 3 #  возведение в степень

In [ ]:
1 / a #  частное 1 и каждого элемента массива

In [ ]:
-a #  изменение знака элементов массива

In [ ]:
a = np.arange(6)
a

In [ ]:
np.sin(a)    #  синус каждого элемента массива

In [ ]:
np.log(a)    #  натуральный логарифм элементов массива

операции  `+=`, `-=`, `*=`, `/=`  не создают новый массив, а изменяют старый:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

In [ ]:
a += 2
a

In [ ]:
a *= 2
a

In [ ]:
#  Вещественный тип ('float64') не может быть 
#  преобразован в целочисленный ('int32'):
# a += b

In [ ]:
#  А вот преобразование целочисленного типа в вещественный возможно
b += a
b

При работе с массивами разного типа, тип результирующего массива приводится к более общему:

In [ ]:
a = np.arange(5)
a

In [ ]:
b = np.linspace(0, 5, 5)
b

In [ ]:
a.dtype

In [ ]:
b.dtype

In [ ]:
c = a + b
c

In [ ]:
c.dtype

Применение логических операций к массивам:

Результатом таких операций является массив булевых значений (`True` и `False`):

In [ ]:
a = np.array([2, 3, 5, 7, 11, 13])
a > 5

In [ ]:
a == 7

In [ ]:
b = np.array([2, 2, 5, 5, 11, 11])
a > b

In [ ]:
a == b

массив и число могут быть операндами самых разных математических выражений:

In [ ]:
a = np.array([1, 2, 3])
(a + 3) * 7

In [ ]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
a + b

In [ ]:
a ** b

In [ ]:
a = np.arange(9).reshape(3, 3)
a

In [ ]:
b = np.arange(9, 0, -1).reshape(3, 3)
b

In [ ]:
a + b

In [ ]:
a ** b

!размеры должны быть не равны, НО должны быть совместимыми. 

Если их размеры совместимы, т.е. один массив может быть растянут до размеров другого, то в дело включается механизм broadcasting массивов NumPy. 

Этот механизм  имеет весьма специфичные нюансы. 

Рассмотрим простой пример:

In [ ]:
a = np.arange(9).reshape(3, 3)
a

In [ ]:
b = np.array([1, 2, 3])
b

In [ ]:
c = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
c

In [ ]:
a * b

In [ ]:
a * c

В данном примере массив `b` может быть растянут до размеров массива `a` и станет абсолютно идентичен массиву `c`. 


Вычисление суммы всех элементов в массиве и прочие унарные операции в NumPy реализованы как методы класса `ndarray`:

In [ ]:
a = np.arange(10)
a

In [ ]:
a.sum()

In [ ]:
a.min()

In [ ]:
a.max()

По умолчанию, эти операции применяются к массиву, как к обычному списку чисел, без учета его ранга (размерности). 

Но если указать в качестве параметра одну из осей `axis`, то вычисления будут производиться именно по ней:

In [ ]:
b = np.arange(16).reshape(4, 4)
b

In [ ]:
b.sum(axis=0)    #  Сумма элементов каждого столбца

In [ ]:
b.sum(axis=1)    #  Сумма элементов каждой строки

In [ ]:
b.min(axis=1)    #  Минимальный элемент каждой строки

In [ ]:
b.max(axis=0)    #  Максимальный элемент каждого столбца

### Значения -inf, inf и nan

вычислим натуральный логарифм массива, среди значений которого есть ноль, не появляется  никакой ошибки, а сам логарифм стал равен значению `-inf` (минус бесконечность). 

:

In [ ]:
import numpy as np

np.log(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


-inf

в NumPy мы даже можем делить на ноль:

In [ ]:
a = np.array([0])
1 / a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([inf])

NumPy предупредил нас о том, что встретил деление на ноль, но тем не менее выдал ответ `inf` (плюс бесконечность). 


В NumPy есть еще одно специальное значение - `nan`. Данное значение выдается тогда, когда результат вычислений не удается определить:

In [ ]:
a = np.array([0, 1, np.inf])
a

array([ 0.,  1., inf])

In [ ]:
np.cos(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in cos
  """Entry point for launching an IPython kernel.


array([1.        , 0.54030231,        nan])

NumPy предупредил о том, что ему попалось недопустимое значение, но ошибки не возникло. 

Дело в том, что в реальных вычислениях значения `nan`, `inf` или `-inf` встречается очень часто.



In [ ]:
np.cos(0)/np.sin(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  """Entry point for launching an IPython kernel.


inf

In [ ]:
np.sin(np.pi/2)/np.cos(np.pi/2)    #  ожидаем значение 0, но...

1.633123935319537e+16

Число `1.633123935319537e+16` появилось потому что в NumPy выполняются арифметические, а не символьные вычисления, т. е. число `π` хранится в памяти компьютера не как знание о том, что это математическая константа с бесконечным количеством десятичных знаков после запятой, а как обычное число с десятичной точкой (десятичная дробь) равная числу `π` с очень маленькой, но все же, погрешностью:

In [ ]:
np.pi    #  значение числа pi в NumPy

3.141592653589793

Если вычисления все же возможны, то NumPy их обязательно выполнит. 



Если вам необходимы точные решения, то лучше обратиться к системам компьютерной алгебры и символьных вычислений, например пакету [SymPy](http://www.sympy.org/en/index.html). 



### Линейная алгебра

[Много функций](https://pyprog.pro/linear_algebra_functions/linalg_functions.html).

Произведение одномерных массивов представляет собой скалярное произведение векторов:

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
np.dot(a, b)

11

Произведение двумерных массивов по правилам линейной алгебры также возможно:

In [ ]:
a = np.arange(2, 6).reshape(2, 2)
a

array([[2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6, 10).reshape(2, 2)
b

array([[6, 7],
       [8, 9]])

In [ ]:
np.dot(a, b)

array([[36, 41],
       [64, 73]])

При этом размеры матриц (массивов) должны быть либо равны, а сами матрицы квадратными, либо быть согласованными, т.е. если размеры матрицы `А` равны `[m,k]`, то размеры матрицы `В` должны быть равны `[k,n]`:

In [ ]:
a = np.arange(2, 8).reshape(2, 3)
a

In [ ]:
b = np.arange(4, 10).reshape(3, 2)
b

In [ ]:
np.dot(a,b)

Также по правилам умножения матриц, мы можем умножить матрицу на вектор (одномерный массив). 

При этом в таком умножении вектор столбец должен находиться справа, а вектор строка слева:

In [ ]:
a = np.array([1, 2, 3])
a

In [ ]:
b = np.arange(4, 10).reshape(3, 2)
b

In [ ]:
np.dot(a, b)

In [ ]:
a = np.arange(1, 3).reshape(2, 1)
a

In [ ]:
b = np.arange(4, 10).reshape(3, 2)
b

In [ ]:
np.dot(b, a)

Квадратные матрицы можно возводить в степень `n` т.е. умнажать сами на себя `n` раз:

In [ ]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.dot(a, a)    #  Равносильно a**2

array([[ 7, 10],
       [15, 22]])

In [ ]:
np.linalg.matrix_power(a, 2)

array([[ 7, 10],
       [15, 22]])

In [ ]:
np.linalg.matrix_power(a, 0)

Довольно часто приходится вычислять ранг матриц:

In [ ]:
a = np.arange(1, 10).reshape(3, 3)
a

In [ ]:
np.linalg.matrix_rank(a)

2

In [ ]:
b = np.arange(1, 24, 2).reshape(3, 4)
b

In [ ]:
np.linalg.matrix_rank(b)

Еще чаще приходится вычислять определитель матриц, хотя результат вас может немного удивить:

In [ ]:
a = np.array([[1, 3], [4, 3]])
a

array([[1, 3],
       [4, 3]])

In [ ]:
np.linalg.det(a)

-8.999999999999998

In [ ]:
1*3 - 3*4    #  Результат должен быть целым числом

В данном случае, из-за двоичной арифметики, результат нецелое число и округлять до ближайшего целого придется вручную. 

Это связано с тем, что алгоритм вычисления определителя использует [LU-разложение](https://ru.wikipedia.org/wiki/LU-%D1%80%D0%B0%D0%B7%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5) - это намного быстрее, чем обычный алгоритм, но за скорость все же приходится немного заплатить ручным округлением (конечно, если таковое требуется):

In [ ]:
np.linalg.det(a)

In [ ]:
round(np.linalg.det(a))

In [ ]:
b = np.arange(1, 48, 3).reshape(4, 4)
b

In [ ]:
np.linalg.det(b)

In [ ]:
round(np.linalg.det(b))

Транспонирование матриц:

In [ ]:
a

In [ ]:
a.T

Вычисление обратных матриц:

In [ ]:
a

In [ ]:
b = np.linalg.inv(a)
b

In [ ]:
np.dot(a, b)

Решение систем линейных уравнений:

In [ ]:
#  система из двух линейных уравнений:
#  1*x1 + 5*x2 = 11
#  2*x1 + 3*x2 = 8
a = np.array([[1, 5], [2, 3]])
b = np.array([11, 8])

In [ ]:
x = np.linalg.solve(a, b)
x

array([1., 2.])

In [ ]:
np.dot(a, x)

array([11.,  8.])

### Статистика

[Элементарные статистические функции](https://pyprog.pro/statistics_functions/statistics_function.html):

In [ ]:
a = np.random.randint(200, size=(5, 5))
a

array([[ 72,  34, 171, 186, 153],
       [156, 172,  90, 178,  63],
       [ 68,  68, 167,  50, 192],
       [133,  17, 144, 187,  61],
       [ 63, 136, 105,  73, 121]])

In [ ]:
np.amin(a)    #  Минимальный элемент массива

In [ ]:
np.amax(a)    #  максимальный элемент

In [ ]:
np.amin(a, axis=0)  #  минимальный элемент вдоль первой оси (столбцы)

In [ ]:
np.amin(a, axis=1)  #  минимальный элемент вдоль второй оси (строки)

In [ ]:
#  Процентили:
np.percentile(a, 25)

68.0

In [ ]:
np.percentile(a, 50)

121.0

In [ ]:
np.percentile(a, 75)

167.0

Средние значения элементов массива и их отклонения:

In [ ]:
a = np.random.randint(13, size=(5, 5))
a

In [ ]:
np.median(a)    #  медиана элементов массива

In [ ]:
np.mean(a)    #  среднее арифметическое

In [ ]:
np.var(a)    #  дисперсия

2857.6

In [ ]:
np.std(a)    #  стандартное отклонение

53.45652439132196

Корреляционные коэфициенты и ковариационные матрицы величин:

In [ ]:
x = np.array([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = np.array([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])
z = np.array([29, 22, 24, 20, 18, 14, 16, 11, 9, 10])

In [ ]:
#  Линейный коэфициент корреляции Пирсона
#  величин 'x' и 'y'

XY = np.stack((x, y), axis=1)
XY

array([[ 1,  4],
       [ 4,  1],
       [ 3,  6],
       [ 7,  9],
       [10, 13],
       [ 8, 11],
       [14, 16],
       [21, 19],
       [20, 15],
       [23, 22]])

In [ ]:
np.corrcoef(XY)

In [ ]:
#  Кросс-корреляции:
np.correlate(x, y)

array([1736])

In [ ]:
np.correlate(x, z)

array([1486])

In [ ]:
#  Ковариационные матрицы:
np.cov(XY)

array([[ 4.5, -4.5,  4.5,  3. ,  4.5,  4.5,  3. , -3. , -7.5, -1.5],
       [-4.5,  4.5, -4.5, -3. , -4.5, -4.5, -3. ,  3. ,  7.5,  1.5],
       [ 4.5, -4.5,  4.5,  3. ,  4.5,  4.5,  3. , -3. , -7.5, -1.5],
       [ 3. , -3. ,  3. ,  2. ,  3. ,  3. ,  2. , -2. , -5. , -1. ],
       [ 4.5, -4.5,  4.5,  3. ,  4.5,  4.5,  3. , -3. , -7.5, -1.5],
       [ 4.5, -4.5,  4.5,  3. ,  4.5,  4.5,  3. , -3. , -7.5, -1.5],
       [ 3. , -3. ,  3. ,  2. ,  3. ,  3. ,  2. , -2. , -5. , -1. ],
       [-3. ,  3. , -3. , -2. , -3. , -3. , -2. ,  2. ,  5. ,  1. ],
       [-7.5,  7.5, -7.5, -5. , -7.5, -7.5, -5. ,  5. , 12.5,  2.5],
       [-1.5,  1.5, -1.5, -1. , -1.5, -1.5, -1. ,  1. ,  2.5,  0.5]])

In [ ]:
np.cov(x)

array(63.65555556)

Так же NumPy предоставляет функции для вычисления гистограмм наборов данных различной размерности и некоторые другие статистичские функции.

### Генерация случайных значений

Получение простых случайных данных:

In [ ]:
np.random.rand()    #  случайное число от 0 до 1

0.03531268624747008

In [ ]:
np.random.rand(10)    #  одномерный массив случайных значений

array([0.69194585, 0.03302362, 0.27109954, 0.29604165, 0.76997087,
       0.9066475 , 0.30879373, 0.65730638, 0.40157416, 0.28751768])

In [ ]:
np.random.rand(4, 4)    #  двумерный массив случайных значений

array([[0.96830433, 0.12691256, 0.88004409, 0.40875406],
       [0.1153612 , 0.63423812, 0.53466323, 0.6633678 ],
       [0.341734  , 0.87080408, 0.55916858, 0.89655809],
       [0.15120441, 0.5007431 , 0.14022154, 0.21469991]])

In [ ]:
np.random.randn(10)    #  случайные значения с нормальным распределением

In [ ]:
np.random.randint(10)    #  случайное целое число от 0 до 10

In [ ]:
np.random.randint(10, 100)    #  случайное целое число от 10 до 100

In [ ]:
np.random.randint(10, size=7)    #  одномерный массив случайных целых чисел

In [ ]:
np.random.randint(10, size=(4, 4))    #  двумерный массив случайных целых чисел

Перестановки:

In [ ]:
x = np.arange(7)
x

In [ ]:
np.random.shuffle(x)    #  перетасовывает содержимое массива
x

array([ 3,  1,  7, 23, 14, 20,  4, 21, 10,  8])

In [ ]:
np.random.permutation(7)    #  выполняет тоже самое, не требуя входного массива

array([4, 1, 3, 6, 5, 0, 2])

In [ ]:
y = np.arange(9).reshape(3, 3)
y

In [ ]:
np.random.shuffle(y)    #  перестановки выполняются только по 1-й оси

NumPy предоставляет [порядка 30 функций](https://pyprog.pro/random_sampling_functions/random_sampling_functions.html), позволяющих генерировать случайные числа с самыми разными вероятностными распределениями:

In [ ]:
np.random.beta(0.1, 0.6, size=5)    #  бета распределение

array([5.14588126e-02, 1.08249428e-08, 1.13499722e-01, 4.72836587e-03,
       2.67697709e-02])

In [ ]:
np.random.gamma(shape=0.8, scale=1.7, size=5)    # гамма распределение

array([0.84068412, 2.0062939 , 2.87326476, 2.35582399, 1.1962259 ])

In [ ]:
np.random.pareto(3.5, size=5)    #  Паретто распределение

array([0.06709345, 0.11129089, 0.13330934, 0.0447309 , 0.11014842])

In [ ]:
np.random.chisquare(2.2, size=5)     #  хи-квадрат распределение

array([1.43499733, 5.00922893, 2.57464691, 4.71706516, 1.93135515])

Вы так же имеете доступ к состоянию генератора случайных чисел, а так же можете управлять им:

In [ ]:
#np.random.get_state()    #  Вы можете узнать состояние генератора

In [ ]:
np.random.seed(123)    #  устанавливает состояние генератора

In [ ]:
np.random.rand(5)

### Множества

В случаях, когда массивы содержат очень много элементов, среди которых есть одинаковые, возникает задача поиска уникальных элементов, количества их вхождений в исходный массив:

In [ ]:
x = np.array([1, 2, 1, 2, 3, 1])
np.unique(x)

array([1, 2, 3])

In [ ]:
np.unique(x, return_counts=True)    #  количество вхождений

В двумерных и многомерных массивах уникальные массивы можно искать, как по всему множеству его значений, так и по отдельным осям:

In [ ]:
x = np.array([[0, 1, 1, 2], [0, 1, 1, 2], [9, 1, 1, 2]])
x

In [ ]:
np.unique(x, axis=0)    #  множество уникальных строк

In [ ]:
np.unique(x, axis=1)    #  множество уникальных столбцов

Так же имеется ряд других полезных функций:

In [ ]:
X = np.array([0, 2, 4, 6, 8])
Y = np.array([0, 3, 4, 6, 7])

In [ ]:
np.in1d(X, Y)    #  наличие элементов из X среди элементов Y

array([ True, False,  True,  True, False])

In [ ]:
np.intersect1d(X, Y)    #  пересечение множеств элементов массивов

array([0, 4, 6])

In [ ]:
np.setdiff1d(X, Y)    #  разность множеств

In [ ]:
np.setxor1d(X, Y)    #  симметрическая разность (исключающее или)

In [ ]:
np.union1d(X, Y)     #  объединение множеств

### Логические операции

Логические функции NumPy, условно, можно разделить на два множества: первое - позволяет определять специфику элементов массива и самого массива; второе - обычные логические операции, которые действуют над массивами поэлементно.

Иногда, возникает потребность определить тип элементов:

In [ ]:
A = np.array([-np.inf, np.inf, np.nan, -1, 0, 1, 1.47, 2, 3 + 2j])

In [ ]:
np.isfinite(A)    #  Все ли элементы в A числа?

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [ ]:
np.isinf(A)    #  Есть ли в A бесконечности?

array([ True,  True, False, False, False, False, False, False, False])

In [ ]:
np.isnan(A)    #  Есть ли в A значения nan?

array([False, False,  True, False, False, False, False, False, False])

In [ ]:
np.iscomplex(A)    #  есть ли в A комплексные числа?

array([False, False, False, False, False, False, False, False,  True])

In [ ]:
np.isreal(A)    #  Есть ли в A вещественные числа?

array([ True,  True,  True,  True,  True,  True,  True,  True, False])

Привычные нам логические операции выполняются над массивами булевых значений (массивы из значений True и False):

In [ ]:
X = np.array([True, False, True, False])
Y = np.array([True, True, False, False])

In [ ]:
np.logical_and(X, Y)    #  логическое "И"

array([ True, False, False, False])

In [ ]:
np.logical_or(X, Y)    #  логическое "ИЛИ"

array([ True,  True,  True, False])

In [ ]:
np.logical_not(X)    #  логическое "НЕ"

array([False,  True, False,  True])

In [ ]:
np.logical_xor(X, Y)    # исключающее "ИЛИ"

array([False,  True,  True, False])

Помимо всего прочего, NumPy позволяет производить различные сравнения:

In [ ]:
np.allclose([1, 2, 3], [1, 2, 2.99999])    #  Являются ли значения массивов близкими?

In [ ]:
x = np.random.randint(4, size=5)
x

array([1, 1, 0, 0, 1])

In [ ]:
y = np.random.randint(4, size=5)
y

array([1, 0, 3, 1, 0])

In [ ]:
np.greater(x, y)    #  поэлементное x > y 

array([False,  True, False, False,  True])

In [ ]:
np.less(x, y)    #  поэлементное x < y

array([False, False,  True,  True, False])

In [ ]:
np.equal(x, y)    #  поэлементное x == y

array([ True, False, False, False, False])

In [ ]:
np.argmax(y)

2