#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [452]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [453]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Как узнать объем памяти любого массива (★☆☆)

In [454]:
print(v.nbytes)

80


#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [455]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

In [456]:
v = np.flip(v)
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [457]:
mx3x3 = np.arange(9).reshape((3,3))
print(mx3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)

In [458]:
v = np.array([1,2,0,0,4,0])
print(v.nonzero())


(array([0, 1, 4], dtype=int64),)


#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [459]:
tz3x3x3 = np.random.random((3, 3, 3))
print(tz3x3x3)

[[[0.69668409 0.5064981  0.21986741]
  [0.22076972 0.00329166 0.65387855]
  [0.40511169 0.04442626 0.15427038]]

 [[0.68507393 0.7965188  0.22854669]
  [0.15052977 0.53727368 0.46573508]
  [0.66965515 0.2197433  0.00330009]]

 [[0.27860945 0.67140013 0.90364512]
  [0.6882043  0.46276448 0.67853112]
  [0.81579467 0.7494169  0.85611646]]]


#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [460]:
mx10x10 = np.random.random((10, 10))
print(mx10x10)
print("Min:", mx10x10.min(), "Max:", mx10x10.max())

[[9.66904014e-01 4.61831906e-01 3.90090820e-01 7.33349225e-01
  3.71381615e-01 5.65550375e-01 6.85099394e-01 2.25626567e-01
  9.02129207e-01 9.86729522e-01]
 [4.78162203e-01 3.23551027e-01 4.60472594e-04 5.43369394e-01
  6.02286880e-01 1.25322824e-01 6.38711061e-01 2.69505746e-02
  4.35676209e-01 1.36953010e-01]
 [9.14233807e-01 8.68681086e-01 1.21661206e-01 1.18670330e-01
  1.46169648e-01 2.03893942e-01 6.26359593e-01 4.63295635e-01
  5.35925866e-01 3.10786312e-02]
 [4.10044867e-01 8.84090385e-01 3.70983496e-02 5.97662024e-01
  3.85202789e-02 7.11585668e-01 4.86385674e-01 1.26088772e-01
  6.15540989e-02 3.45241400e-01]
 [7.19648150e-01 3.22119289e-01 8.73138738e-01 8.84826349e-01
  8.78365468e-03 5.52649292e-01 4.79809379e-01 5.01859010e-02
  6.25112727e-01 9.76366207e-01]
 [3.14850567e-02 3.88295151e-01 5.85050739e-01 1.72792490e-01
  5.38679452e-01 2.88526930e-01 4.01042775e-01 3.35130105e-01
  4.92994890e-01 7.46266093e-01]
 [1.75758335e-01 6.46038156e-01 8.54578947e-01 1.36205542e

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [461]:
v = np.random.random(30)
print(v)
print("Mean:", v.mean())

[0.70303334 0.33566854 0.93461698 0.02251979 0.1122137  0.53067173
 0.89113425 0.45610848 0.94850287 0.05211534 0.32857188 0.87685062
 0.48827177 0.26482231 0.79494396 0.289358   0.01845011 0.03308918
 0.78036031 0.20965634 0.38329759 0.92183518 0.87028818 0.02962445
 0.69749603 0.07252294 0.47548996 0.45693079 0.92633739 0.75828269]
Mean: 0.48876882239947067


#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)

In [462]:
mx2x3 = np.tile(np.array([1,0,1]), 2).reshape(2,3)
print(mx2x3)

mx10x10 = np.ones((10, 10))
mx10x10[1:-1, 1:-1] = 0
print(mx10x10)

[[1 0 1]
 [1 0 1]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [463]:
r1 = 0 * np.nan
r2 = np.nan == np.nan
r3 = np.inf > np.nan
r4 = np.nan - np.nan
r5 = np.nan in set([np.nan])
r6 = 0.3 == 3 * 0.1
print("Expr1 =", r1)
print("Expr2 =", r2)
print("Expr3 =", r3)
print("Expr4 =", r4)
print("Expr5 =", r5)
print("Expr6 =", r6)

Expr1 = nan
Expr2 = False
Expr3 = False
Expr4 = nan
Expr5 = True
Expr6 = False


#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [464]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [465]:
mx5x3 = np.ones((5,3))
mx3x2 = np.ones((3,2))
print(np.dot(mx5x3, mx3x2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [466]:
vF = np.random.randint(1, 11, size=100)
vI = vF

#flip
print("Raw array:", vF, "\n")

idx3 = np.array(np.where(vF == 3))
idx8 = np.array(np.where(vF == 8))
print("Where 3 size", idx3.size, "values:",idx3)
print("Where 8 size", idx8.size, "values:",idx8)

if idx3.size != idx8.size:
    ___arraysize = min(idx3.size, idx8.size)
    idx3.resize(___arraysize, refcheck=False)
    idx8.resize(___arraysize, refcheck=False)
pairs = np.vstack((idx3, idx8)).T
print("Pairs to swap:\n", pairs, "\n")

for __pair in pairs:
    vF[__pair[0]], vF[__pair[1]] = vF[__pair[1]], vF[__pair[0]]
print("Fliped 3 to 8 array:", vF)

#invert
vI[vI == 3] = -1
vI[vI == 8] = 3
vI[vI == -1] = 8
print("\nInverted 3 and 8 array:", vI)

Raw array: [ 3  4  9 10  8  2  4  5  6  9 10  5  8  8  5  4  3  1  9  6  2  1  3  2
 10  6  3  7  6  8  6  9  9  9  7  7  6  6  2  6  4  2  1  1  1  1  4 10
  3  9  4 10  3  7 10  1 10  3  3  8  2  9  4 10  9  9  9  2  4  4  2  4
  6  3  1  1  1  8  8  9  6  9  5  2  9  5  1  2  1  4  3  1  6  5  8  2
  9  8  8  2] 

Where 3 size 10 values: [[ 0 16 22 26 48 52 57 58 73 90]]
Where 8 size 10 values: [[ 4 12 13 29 59 77 78 94 97 98]]
Pairs to swap:
 [[ 0  4]
 [16 12]
 [22 13]
 [26 29]
 [48 59]
 [52 77]
 [57 78]
 [58 94]
 [73 97]
 [90 98]] 

Fliped 3 to 8 array: [ 8  4  9 10  3  2  4  5  6  9 10  5  3  3  5  4  8  1  9  6  2  1  8  2
 10  6  8  7  6  3  6  9  9  9  7  7  6  6  2  6  4  2  1  1  1  1  4 10
  8  9  4 10  8  7 10  1 10  8  8  3  2  9  4 10  9  9  9  2  4  4  2  4
  6  8  1  1  1  3  3  9  6  9  5  2  9  5  1  2  1  4  8  1  6  5  3  2
  9  3  3  2]

Inverted 3 and 8 array: [ 3  4  9 10  8  2  4  5  6  9 10  5  8  8  5  4  3  1  9  6  2  1  3  2
 10  6  3  7  6  8  6  9  9  9 

#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [467]:
r7 = np.array(0) / np.array(0)
r8 = np.array(0) // np.array(0)
r9 = np.array([np.nan]).astype(int).astype(float)
print("Expr7 =", r7)
print("Expr8 =", r8)
print("Expr9 =", r9)

Expr7 = nan
Expr8 = 0
Expr9 = [-2.14748365e+09]


C:\Users\leysh\AppData\Local\Temp\ipykernel_21060\1842360515.py:1: RuntimeWarning: invalid value encountered in true_divide
  r7 = np.array(0) / np.array(0)
C:\Users\leysh\AppData\Local\Temp\ipykernel_21060\1842360515.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  r8 = np.array(0) // np.array(0)


#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [468]:
a1 = np.array(np.arange(15))
a2 = np.array(np.arange(0, 30, 2))
print("Array1:", a1)
print("Array2:", a2)

#in1d
print("Array from in1d:", a1[np.in1d(a1, a2)])

#intersect1d
print("Array from intersect1d", np.intersect1d(a1, a2))

Array1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Array2: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
Array from in1d: [ 0  2  4  6  8 10 12 14]
Array from intersect1d [ 0  2  4  6  8 10 12 14]


#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [469]:
vSize = 10
A = np.random.random(vSize)
idA = id(A)
print("A id =", id(A), ":", A)

B = np.random.random(vSize)
idB = id(B)
print("B id =", id(B), ":", B)

np.add(A, B, B)
print("Step1 result in B id = ", id(B), ":", B)

np.divide(A, -2, A)
print("Step2 result in A id = ", id(A), ":", A)

np.multiply(B, A, A)
print("Step3 result in A id = ", id(A), ":", A)
print("\nID A on init", idA, "and now", id(A))
print("ID B on init", idB, "and now", id(B))

A id = 2727842507984 : [0.7775695  0.65638842 0.54402141 0.7895931  0.88352937 0.10497442
 0.87703216 0.62654731 0.71559185 0.08128064]
B id = 2727842507024 : [0.57675542 0.58515828 0.49888545 0.00444669 0.80870054 0.3311548
 0.31813763 0.84158172 0.73069091 0.1780169 ]
Step1 result in B id =  2727842507024 : [1.35432492 1.2415467  1.04290686 0.79403979 1.69222992 0.43612922
 1.19516979 1.46812903 1.44628275 0.25929754]
Step2 result in A id =  2727842507984 : [-0.38878475 -0.32819421 -0.2720107  -0.39479655 -0.44176469 -0.05248721
 -0.43851608 -0.31327366 -0.35779592 -0.04064032]
Step3 result in A id =  2727842507984 : [-0.52654087 -0.40746844 -0.28368183 -0.31348417 -0.74756742 -0.02289121
 -0.52410117 -0.45992615 -0.51747407 -0.01053793]

ID A on init 2727842507984 and now 2727842507984
ID B on init 2727842507024 and now 2727842507024


#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [470]:
mx5x5 = np.tile(np.arange(5),5).reshape((5,5))
print(mx5x5)

mx5x5B = np.zeros((5,5), dtype=np.int32) + np.arange(5)
print(mx5x5B)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [471]:
v = np.random.uniform(low=0.00000001, high=1, size=10)
print(v)

vL = np.linspace(0, 1, 12)[1:-1]
print(vL)

[0.72832432 0.0350078  0.68905701 0.4445822  0.86237784 0.22496758
 0.9711608  0.25389052 0.07148142 0.06373099]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [472]:
v = np.random.rand(10)
print(v)
v.sort()
print(v)


[0.5273065  0.57420973 0.95854937 0.83968759 0.13447985 0.64171683
 0.13105418 0.58676069 0.64739743 0.0077363 ]
[0.0077363  0.13105418 0.13447985 0.5273065  0.57420973 0.58676069
 0.64171683 0.64739743 0.83968759 0.95854937]


#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [473]:
nSize = 100
vToSumm = np.random.uniform(0, 100, nSize)
vSumList = vToSumm.tolist()

In [474]:
%%timeit
np.sum(vToSumm)

2.68 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [475]:
%%timeit
np.sum(vSumList)

7.86 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [476]:
%%timeit
sum(vSumList)

345 ns ± 11.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [477]:
%%timeit
s = 0
for __e in vToSumm:
    s += __e

6.26 µs ± 162 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [478]:
%%timeit
s = 0
for __e in vSumList:
    s += __e

1.81 µs ± 23.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [479]:
A = np.random.randint(0, 2, 2)
B = np.random.randint(0, 2, 2)
print("A:", A)
print("B:", B)
print("Equal by element:", np.equal(A, B))
print("Equal total:", np.array_equal(A, B))

A: [1 0]
B: [0 1]
Equal by element: [False False]
Equal total: False


#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [480]:
v = np.random.random(10)
print("Base:", v)
v[v.max() == v] = 0
print("Replaced max:", v)

Base: [0.5267077  0.71612476 0.94521723 0.56135539 0.14000446 0.38687439
 0.63909328 0.92847792 0.4319499  0.18865229]
Replaced max: [0.5267077  0.71612476 0.         0.56135539 0.14000446 0.38687439
 0.63909328 0.92847792 0.4319499  0.18865229]


#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [481]:
for t in np.ScalarType:
    try:
        ti = np.iinfo(t)
        print("Type:", ti.dtype, "Max:", ti.max, "Min", ti.min)
    except: pass

Type: int32 Max: 2147483647 Min -2147483648
Type: int32 Max: 2147483647 Min -2147483648
Type: int8 Max: 127 Min -128
Type: int16 Max: 32767 Min -32768
Type: int32 Max: 2147483647 Min -2147483648
Type: int32 Max: 2147483647 Min -2147483648
Type: int64 Max: 9223372036854775807 Min -9223372036854775808
Type: uint8 Max: 255 Min 0
Type: uint16 Max: 65535 Min 0
Type: uint32 Max: 4294967295 Min 0
Type: uint32 Max: 4294967295 Min 0
Type: uint64 Max: 18446744073709551615 Min 0


#### 26. Как вывести все значения большого массива? (★★☆)

In [482]:
# not affects to VSCode option: notebook.output.textLineLimit
with np.printoptions(threshold=np.inf):
    print(vToSumm)

[6.55541540e+00 9.64099707e-03 3.83394986e+01 7.15456394e+01
 2.80599307e+01 3.60080554e+01 3.22256663e+01 7.94149502e+01
 9.24975275e+01 6.94744909e+01 5.67984355e+01 8.36614758e+01
 3.37341667e+01 6.62877390e+01 3.73643491e+01 3.61585349e+01
 7.88639589e+01 7.62888064e+00 3.62582765e+01 5.93511759e+01
 8.54835945e+01 7.90401942e+01 9.63603476e+01 7.29844729e+01
 1.74123997e+01 7.61328125e+01 8.94323580e+01 8.78833527e+01
 6.90298521e+01 9.67755508e+01 6.71953816e+01 9.91750419e+01
 3.33640525e+01 1.03548709e+01 2.10412175e+01 7.04089332e+01
 2.44616834e+01 7.73734621e+01 6.68568770e+00 3.78189154e+01
 9.84282400e+01 6.71621170e+01 6.74268708e+01 8.15995221e+01
 8.05499351e+01 8.89851020e+01 3.42845968e+01 8.44731701e+01
 6.60409831e+01 3.63020608e+01 3.09445992e+01 2.99780790e+01
 6.35551751e+01 9.60787814e+01 2.24518970e+01 9.64406929e+01
 2.88037304e+01 8.92016625e+01 6.10997565e+01 6.95026487e+01
 7.75116203e+01 3.04127470e+00 7.08242699e+01 9.16450566e+01
 7.79998178e+01 3.847285

#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [483]:
def euqDistPtToArr(pt1Arr, pt2):
    #sqrt((x1 - x2)**2 + (y1 - y2)**2) 
    return np.sqrt(np.square(pt1Arr[:,0].T - pt2[0]) + np.square(pt1Arr[:,1].T - pt2[1]))

In [484]:
mx100x2 = np.random.random((100, 2))
nSize = mx100x2.shape[0]
mxDist = np.ones((nSize, nSize))

for idx in np.arange(nSize):
    mxDist[idx,:] = euqDistPtToArr(mx100x2, mx100x2[idx])

with np.printoptions(threshold=np.inf):
    np.disp(mxDist)

[[0.         0.83850272 0.31037734 0.47080589 0.91893297 0.79527621
  0.64570062 0.6033851  0.27656392 0.92852477 0.73958626 0.72047891
  0.68915008 0.58894785 0.87502467 1.0170119  0.67146261 0.51542893
  0.76678257 0.30808382 0.69130046 0.76837754 0.29846847 0.74803123
  0.79200341 0.84651737 0.0657066  0.29062629 0.62098658 0.57978631
  0.64852516 0.5974911  0.71504388 0.32313158 0.70262558 1.04960967
  0.21950383 0.86586908 0.75714802 0.72554939 0.89459025 0.17459771
  0.89000583 0.47726827 0.18677586 0.78368062 1.20431666 0.24525401
  0.67762623 0.44534657 1.06970165 0.70151952 0.55340268 0.67122115
  0.8001219  0.45898363 0.32453722 0.93345363 0.93204773 0.84863609
  0.80858091 0.93368948 0.74167176 0.9116907  0.70532287 1.03572346
  0.56215539 1.02123298 1.02651539 0.74383478 1.00677386 0.75056674
  0.96842603 0.77322167 0.78112231 0.76035819 0.49354677 0.8080504
  0.85155497 0.28535335 0.59766277 0.7956776  0.88595208 0.13705892
  0.6728007  0.4603334  0.40434079 0.40359265 0.4

#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [485]:
v = np.arange(1, 5, 0.5, dtype=np.float32)
idV = id(v)
def printV(txt, __v):
    print(txt, __v.dtype, "id =", id(__v), "(", idV == id(__v) ,")", __v)
v1 = v.astype(np.float64, copy = True)
printV("Base array type = ", v)
vf1 = v.astype(np.int32, order='C',subok=False, copy=False)
vf2 = v.astype(np.int32, order='F',subok=False, copy=False)
vf3 = v.astype(np.int32, order='A',subok=False, copy=False)
vf4 = v.astype(np.int32, order='K',subok=False, copy=False)
vt1 = v.astype(np.int32, order='C',subok=True, copy=False)
vt2 = v.astype(np.int32, order='F',subok=True, copy=False)
vt3 = v.astype(np.int32, order='A',subok=True, copy=False)
vt4 = v.astype(np.int32, order='K',subok=True, copy=False)

printV("Cast Array type = ", v1)
printV("vf1", vf1)
printV("vf2", vf2)
printV("vf3", vf3)
printV("vf4", vf4)
printV("vt1", vt1)
printV("vt2", vt2)
printV("vt3", vt3)
printV("vt4", vt4)
# мб не понял что значит заменить, если без копирования то не выходит


Base array type =  float32 id = 2727847835184 ( True ) [1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Cast Array type =  float64 id = 2727911922000 ( False ) [1.  1.5 2.  2.5 3.  3.5 4.  4.5]
vf1 int32 id = 2727911931312 ( False ) [1 1 2 2 3 3 4 4]
vf2 int32 id = 2727911922096 ( False ) [1 1 2 2 3 3 4 4]
vf3 int32 id = 2727911922288 ( False ) [1 1 2 2 3 3 4 4]
vf4 int32 id = 2727911922480 ( False ) [1 1 2 2 3 3 4 4]
vt1 int32 id = 2727911923440 ( False ) [1 1 2 2 3 3 4 4]
vt2 int32 id = 2727911922960 ( False ) [1 1 2 2 3 3 4 4]
vt3 int32 id = 2727911923536 ( False ) [1 1 2 2 3 3 4 4]
vt4 int32 id = 2727911930160 ( False ) [1 1 2 2 3 3 4 4]


#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [486]:
from io import StringIO   # StringIO behaves like a file object
fileSimulation = StringIO("1, 2, 3, 4, 5 \n6,  ,  , 7, 8\n ,  , 9,10,11")
a = np.loadtxt(fname=fileSimulation, delimiter=',', dtype=np.string_)
print(a)

[[b'1' b' 2' b' 3' b' 4' b' 5 ']
 [b'6' b'  ' b'  ' b' 7' b' 8']
 [b' ' b'  ' b' 9' b'10' b'11']]


#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [487]:
mx10x10 = np.random.random((10, 10))
np.mean(mx10x10, axis=0)

array([0.42201138, 0.51049543, 0.48976084, 0.68625473, 0.44473997,
       0.65651688, 0.41924772, 0.5601568 , 0.57938262, 0.39487273])

#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

In [488]:
A = np.random.randint(10, size=10)
B = np.random.randint(0, 10, 10)
print("Init A:", A)
print("Index:", B)
A[B] += 1
print("Final A:", A)

Init A: [3 8 3 5 1 6 1 1 2 4]
Index: [5 5 7 4 4 0 7 1 7 8]
Final A: [4 9 3 5 2 7 1 2 3 4]


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [489]:
X = np.random.randint(20, size=30)
print("X:", X)
I = np.random.randint(0, 10, 10)
print("I:", I)
F = X[I]
print("F:", F)

X: [ 4 17 17 10  9  8 19 15 18 13  8 13  8 11  5  4 18  4  2 19 12  5 18  7
 13 18  6 11 13 13]
I: [4 8 9 1 0 3 5 0 9 0]
F: [ 9 18 13 17  4 10  8  4 13  4]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [490]:
tnz4 = np.random.randint(10, size=(4,4,4,4))
np.sum(tnz4, axis=(2, 3))

array([[83, 70, 71, 75],
       [84, 66, 60, 59],
       [67, 58, 77, 68],
       [73, 95, 75, 72]])

#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [491]:
nZeros = 3
v = np.array([1, 2, 3, 4, 5], ndmin=2)
nSize = v.size
v = np.hstack((v.T, np.zeros((nSize, nZeros)))).ravel()
print(v)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [492]:
A, B = np.ones((5,5,3)), np.ones((5,5))*2
C = (A.T*B).T
print(C)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [493]:
A = np.arange(-5, 6)
np.percentile(A, 50)

0.0

#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [494]:
Zd1 = np.arange(2, 15)
tRange = np.arange(3)
Zd2 = np.take(Zd1, tRange)
for i in range(Zd1.size - tRange.size + 1):
    Zd2 = np.vstack((Zd2, np.take(Zd1, tRange + i)))
print("Zd1:", Zd1)
print("Zd2:", Zd2)

Zd1: [ 2  3  4  5  6  7  8  9 10 11 12 13 14]
Zd2: [[ 2  3  4]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [495]:
def x(pt):
    return pt[0]
    
def y(pt):
    return pt[1]

def solve(pt1, pt2):
    a = np.row_stack((x(pt1), x(pt2)))
    a = np.column_stack((a, np.ones_like(pt1)))
    b = np.row_stack((y(pt1), y(pt2)))
    return np.linalg.solve(a, b)

def logBool(log, txt, obj):
    if log:
        print(txt, obj)

def cross(pt1, pt2, pt3, log=False):
    line = solve(pt1, pt2)
    if log:
        logBool(log, "Line i from dot P0[i] P1[i]:", line)

    t = y(line) / x(line)
    perp = np.array([t, -t * x(pt3) + y(pt3)])
    if log:
        logBool(log, "Perpendicular to line:", perp)

    m = np.array([[-1], [1]])
    pCrossed = solve(line * m, perp * m)
    if log:
        logBool(log, "Crossed line w perp:", pCrossed)

    maxP, minP = np.max([x(pt1), x(pt2)]), np.min([x(pt1), x(pt2)])
    if x(pCrossed) >= minP and x(pCrossed) <= maxP:
        return pCrossed
    return np.array([np.inf, np.inf]) # retunr inf if out of line

In [496]:
nL, nP = 3, 10
P0, P1, P = np.random.random((nL, 2)), np.random.random((nL, 2)), np.random.random((nP, 2))

mx100x2 = np.random.random((nL, 2))
mxDist = np.ones((nP, nL))

for idx in np.arange(nP):
    #dist to one side
    distP0 = euqDistPtToArr(P0, P[idx])
    
    # dist to other side
    distP1 = euqDistPtToArr(P1, P[idx])
    
    # dist perpendicular to between if exist 
    distCross = np.zeros((nL,2), dtype=np.float64)
    for idxP in np.arange(nL):
        distCross[idxP,:] = cross(P0[idxP], P1[idxP], P[idx], False).ravel()
    distCrossP = euqDistPtToArr(distCross, P[idx])
    
    # set minimum to result
    mxDist[idx,:] = np.array([distP0, distP1, distCrossP]).min(axis=0)

    print("Line ID:", idx, "Dist to P0:", distP0)
    print("Line ID:", idx, "Dist to P1:", distP1)
    print("Line ID:", idx, "Dist to PCross:", distCrossP)
    print("Line ID:", idx, "MIN Dist:", mxDist[idx,:])

print("\nResult (Min distanse from each P to each line):")
with np.printoptions(threshold=np.inf):
    np.disp(mxDist)


Line ID: 0 Dist to P0: [0.69610838 0.6834788  0.40882163]
Line ID: 0 Dist to P1: [0.02205229 0.50856875 0.14741949]
Line ID: 0 Dist to PCross: [       inf 0.30912743        inf]
Line ID: 0 MIN Dist: [0.02205229 0.30912743 0.14741949]
Line ID: 1 Dist to P0: [0.26142785 0.59380238 0.52227193]
Line ID: 1 Dist to P1: [0.42878526 0.61569159 0.34549181]
Line ID: 1 Dist to PCross: [0.08607698 0.35126847        inf]
Line ID: 1 MIN Dist: [0.08607698 0.35126847 0.34549181]
Line ID: 2 Dist to P0: [0.61276176 0.81910695 0.59962067]
Line ID: 2 Dist to P1: [0.25332244 0.30473053 0.3048574 ]
Line ID: 2 Dist to PCross: [       inf 0.03772025        inf]
Line ID: 2 MIN Dist: [0.25332244 0.03772025 0.3048574 ]
Line ID: 3 Dist to P0: [0.36947782 0.32667051 0.3379962 ]
Line ID: 3 Dist to P1: [0.46994454 0.83570562 0.34388967]
Line ID: 3 Dist to PCross: [       inf 0.20982186 0.31643907]
Line ID: 3 MIN Dist: [0.36947782 0.20982186 0.31643907]
Line ID: 4 Dist to P0: [0.73188019 0.64290265 0.35065489]
Line I

#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [497]:
Zd1 = np.arange(2, 15)
tRange = np.arange(4)
Zd2 = np.take(Zd1, tRange)
for i in range(Zd1.size - tRange.size + 1):
    Zd2 = np.vstack((Zd2, np.take(Zd1, tRange + i)))
print("Zd1:", Zd1)
print("Zd2:", Zd2)

Zd1: [ 2  3  4  5  6  7  8  9 10 11 12 13 14]
Zd2: [[ 2  3  4  5]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 40. Найдите ранг случайной матрицы (★★★)

In [498]:
mx = np.random.randint(10, size=(3,6))
np.linalg.matrix_rank(mx)

3

#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [499]:
mx = np.random.randint(0, 10, (10, 10))
print("MX:", mx)
mxFlat = mx.ravel()
mxFlat.sort()
print("MX as sorted vector:", mxFlat)
mxUniq = np.unique(mx)

mxValRangeCount = np.bincount(mxFlat)

for idx in range(mxUniq.shape[0]):
    print("Value:", mxUniq[idx], "Count:", mxValRangeCount[idx])

print("Trend is", np.argmax(mxValRangeCount))

MX: [[7 3 2 1 9 3 7 3 7 5]
 [7 7 2 0 4 1 8 9 6 3]
 [0 4 2 0 1 9 3 7 1 7]
 [0 3 3 7 7 8 5 2 9 0]
 [0 3 0 8 4 6 4 0 9 2]
 [5 8 7 7 9 6 2 1 4 1]
 [5 0 8 9 4 8 3 3 1 9]
 [1 9 2 4 3 2 6 6 2 8]
 [8 5 3 0 5 7 3 7 3 9]
 [3 7 8 5 3 9 9 1 2 8]]
MX as sorted vector: [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 5 5 5 5 5 5 5 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9 9 9]
Value: 0 Count: 10
Value: 1 Count: 9
Value: 2 Count: 10
Value: 3 Count: 16
Value: 4 Count: 7
Value: 5 Count: 7
Value: 6 Count: 5
Value: 7 Count: 14
Value: 8 Count: 10
Value: 9 Count: 12
Trend is 3


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [500]:
shapeA, shapeB = np.array((8,3)), np.array((2,2))
A, B = np.random.randint(0, 7, size=shapeA), np.random.randint(0, 7, size=shapeB)
print("A:\n", A)
print("\nB:\n", B)
print()

r = np.ones(shapeA[0], dtype=np.bool8)
for idx in range(shapeB[0]):
    r *= np.in1d(A, B[idx, :]).reshape(shapeA).max(axis=1)

print("Rows ID:", np.arange(0, r.size)[r], "\nRows Values:\n", A[r, :])


A:
 [[5 6 1]
 [1 0 1]
 [6 3 2]
 [5 1 6]
 [6 2 1]
 [5 6 2]
 [0 3 3]
 [5 5 3]]

B:
 [[5 6]
 [0 6]]

Rows ID: [0 2 3 4 5] 
Rows Values:
 [[5 6 1]
 [6 3 2]
 [5 1 6]
 [6 2 1]
 [5 6 2]]


In [501]:
a, b1, b2 = A[idx,:], B[0], B[1]
print(a, b1, b2)

print(r1)
print(r2)


[1 0 1] [5 6] [0 6]
nan
False


#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [502]:
A, B = np.random.randint(1, 35, size=(6,2)), np.random.randint(1, 25, size=(4, 6))
print("A:", A)
print("B:", B)

print("\nRavels")
print(" Asorted:", np.sort(A.ravel()))
print(" Bsorted:", np.sort(B.ravel()))

print("\nAB union: ", np.union1d(A, B))
print("AB unique:", np.unique(np.append(A, B)))



A: [[18 27]
 [25 21]
 [ 5 12]
 [17 30]
 [27 28]
 [30 30]]
B: [[17  2 18  8 21 20]
 [14  2  6 21 12 15]
 [23  5 16 13 13 23]
 [ 5 24 22 18 10 20]]

Ravels
 Asorted: [ 5 12 17 18 21 25 27 27 28 30 30 30]
 Bsorted: [ 2  2  5  5  6  8 10 12 13 13 14 15 16 17 18 18 20 20 21 21 22 23 23 24]

AB union:  [ 2  5  6  8 10 12 13 14 15 16 17 18 20 21 22 23 24 25 27 28 30]
AB unique: [ 2  5  6  8 10 12 13 14 15 16 17 18 20 21 22 23 24 25 27 28 30]
