 NumPy - векторные/научные вычисления. Объект **NumPy** - это однородный многомерный массив. 





In [ ]:
import numpy as np # Подключаем библиотеку numpy

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
a = np.array([4, 8, 15, 16, 23, 42])
a.shape

(6,)

Векторизованные вычисления:
Векторизованные - означает, что все арифметические операции и математические функции выполняются сразу над всеми элементами массивов без циклов. 

In [ ]:
b = [4, 8, 15, 16, 23, 42]
y = 2*a + 10
y

array([18, 26, 40, 42, 56, 94])

In [ ]:
np.sin(a)**2 + np.cos(a)**2

array([1., 1., 1., 1., 1., 1.])

In [ ]:
a.ndim

1


2- мерныe массивы

In [ ]:
a = np.arange(12) # функция np.arange(),  во многом аналогична функции range() языка Python. 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a = a.reshape(3, 4) # изменили форму массива с помощью метода `reshape()
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

![image](https://raw.githubusercontent.com/dm-fedorov/numpy_basic/master/pic/2nd_array.jpg)

Глядя на картинку, становится понятно, что первая ось (и индекс соответственно) - это строки, вторая ось - это столбцы. Т.е. получить элемент 9 можно простой командой:

In [ ]:
a[:,:]    #  равносильно команде a[2, 1]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Broadcasting *транслирование массивов*:

In [ ]:
b = [2, 3, 4, 5]

a * b

np.dot(a,b)

array([[ 0,  3,  8, 15],
       [ 8, 15, 24, 35],
       [16, 27, 40, 55]])

 мы умножили каждый столбец из массива `a` на соответствующий элемент из массива `b`. 


In [ ]:
a = np.random.randint(0, 15, size=(4, 6))
a

Минимальный элемент :

In [ ]:
a.min()

минимальные элементы по столбцам и строкам:

In [ ]:
a.max(axis=1)    #  минимальные элементы по столбцам

array([ 3,  7, 11])

In [ ]:
a.min(axis=1)    #  минимальные элементы по строкам

Это поведение заложено практически во все функции и методы NumPy:

In [ ]:
a.mean(axis=0)    #  среднее по столбцам

In [ ]:
np.std(a, axis=1)    #  стандартное отклонение по строкам

трехмерный массив:

In [ ]:
a = np.arange(4915200*2*20).reshape(20,10,10,128,128,3,2,1)
a.ndim

8

In [ ]:
a[1,2,3,:,:,:,:] #RGB

array([[[[[12091392],
          [12091393]],

         [[12091394],
          [12091395]],

         [[12091396],
          [12091397]]],


        [[[12091398],
          [12091399]],

         [[12091400],
          [12091401]],

         [[12091402],
          [12091403]]],


        [[[12091404],
          [12091405]],

         [[12091406],
          [12091407]],

         [[12091408],
          [12091409]]],


        ...,


        [[[12092142],
          [12092143]],

         [[12092144],
          [12092145]],

         [[12092146],
          [12092147]]],


        [[[12092148],
          [12092149]],

         [[12092150],
          [12092151]],

         [[12092152],
          [12092153]]],


        [[[12092154],
          [12092155]],

         [[12092156],
          [12092157]],

         [[12092158],
          [12092159]]]],



       [[[[12092160],
          [12092161]],

         [[12092162],
          [12092163]],

         [[12092164],
          [12092165]]],


   

![image](https://raw.githubusercontent.com/dm-fedorov/numpy_basic/master/pic/3nd_array.jpg)

индексация трехмерных массивов:

In [ ]:
a[2][1][3]    #  или a[2, 1, 3]

In [ ]:
a.ndim

8

In [ ]:
a.shape # форма массива

(20, 10, 10, 128, 128, 3, 2, 1)

In [ ]:
a.dtype

dtype('int64')

Метод `ndarray.size` просто возвращает общее количество элементов массива:

In [ ]:
a.size

сколько "весит" один элемент массива:

In [ ]:
a.itemsize    #  эквивалентно ndarray.dtype.itemsize

8

`ndarray.itemsize` возвращает размер элемента в байтах. 

Теперь мы можем узнать сколько "весит" наш массив:

In [ ]:
a.size * a.itemsize /1024/1024

1500.0

Итого - 384 байта. 

In [ ]:
a.dtype

`dtype('int64')` - означает, что используется целочисленный тип данных, в котором для хранения одного числа выделяется 64 бита памяти. 

Но если мы выполним какие-нибудь вычисления с массивом, то тип данных может измениться:

In [ ]:
b = a/3.14 
b

array([[[[[[[[0.00000000e+00],
             [3.18471338e-01]],

            [[6.36942675e-01],
             [9.55414013e-01]],

            [[1.27388535e+00],
             [1.59235669e+00]]],


           [[[1.91082803e+00],
             [2.22929936e+00]],

            [[2.54777070e+00],
             [2.86624204e+00]],

            [[3.18471338e+00],
             [3.50318471e+00]]],


           [[[3.82165605e+00],
             [4.14012739e+00]],

            [[4.45859873e+00],
             [4.77707006e+00]],

            [[5.09554140e+00],
             [5.41401274e+00]]],


           ...,


           [[[2.38853503e+02],
             [2.39171975e+02]],

            [[2.39490446e+02],
             [2.39808917e+02]],

            [[2.40127389e+02],
             [2.40445860e+02]]],


           [[[2.40764331e+02],
             [2.41082803e+02]],

            [[2.41401274e+02],
             [2.41719745e+02]],

            [[2.42038217e+02],
             [2.42356688e+02]]],


           [

In [ ]:
b.dtype

dtype('float64')

In [ ]:
del a, b

In [ ]:
import gc
gc.collect()

175

### Создание массивов в NumPy

[Большой обзор функций для создания массивов](https://pyprog.pro/array_creation/array_creation_functions.html)


В NumPy реализованы свои типы данных, которые отличаются от встроенных в Python.

Подробнее о типах: https://docs.scipy.org/doc/numpy/user/basics.types.html

In [ ]:
import numpy as np

a = np.array([1, 2, 3]) # массив может быть создан из обычного списка или кортежа Python с использованием функции `array()`. 
a

In [ ]:
numpy2 = np.array([1, 2, 3, 4, 5, 6]) # Создаем numpy-массив из списка цифр
print(numpy2) # Выводим на экран массив numpy2
print(numpy2.shape) # Выводим на экран размерность массива numpy2

[1 2 3 4 5 6]
(6,)


In [ ]:
numpy_new = numpy2.reshape((3, 2)) # Изменяем размерность массива numpy2 из (6,) -> (3, 2)
print(numpy_new) # Выводим на экран массив numpy_new

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
6.26140102e+07 

In [ ]:
a.dtype # тип полученного массива зависит от типа элементов последовательности:

NameError: ignored

In [ ]:
a = np.array([1.1, 2.2, 3.3],dtype='float32')
a

array([1.1, 2.2, 3.3], dtype=float32)

In [ ]:
a.dtype

dtype('float32')

In [ ]:
a = np.array([1 + 2j, 2 + 3j])
a.dtype

dtype('complex128')

In [ ]:
a = np.array([1, 2, 3, 2 + 3j])
a

array([1.+0.j, 2.+0.j, 3.+0.j, 2.+3.j])

Функция `array()` преобразует последовательности последовательностей в двумерные массивы, а последовательности последовательностей, которые тоже состоят из последовательностей в трехмерные массивы.

уровень вложенности исходной последовательности определяет размерность получаемого массива:

In [ ]:
a = np.array([[2, 4,3], [6, 8,1], [10, 12,6]])
a

array([[ 2,  4,  3],
       [ 6,  8,  1],
       [10, 12,  6]])

In [ ]:
b = np.array([[[1, 2], [3, 4]], 
              [[5, 6], [7, 8]], 
              [[9, 10], [11, 12]]])
b

In [ ]:
a.ndim    #  Количество осей массива

In [ ]:
b.ndim



Функция `zeros` заполняет массив нулями, функция `ones` - единицами, а функция `empty` - случайными числами, которые зависят от состояния памяти. 

По умолчанию, тип создаваемого массива - `float64`.

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,3), dtype=complex)  #  Можно изменить тип массива

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

In [ ]:
np.empty([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Для создания последовательностей чисел NumPy предоставляет функцию `arange`, которая возвращает одномерные массивы:

In [ ]:
np.arange(10)    #  От 0 до указанного числа

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 20)    #  Диапазон

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20, 100, 10)    #  Диапазон с заданным шагом

array([20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(0.0, 1.8)    #  Аргументы могут иметь тип float

array([0., 1.])

Если функция `arange` используется с аргументами типа `float`, то предсказать количество элементов в возвращаемом массиве не так-то просто. 



Функция `linspace`, так же как и `arange` принимает три аргумента,  третий аргумент указывает количество чисел в диапазоне.

In [ ]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
np.linspace(0, 1, 7)

In [ ]:
np.linspace(10, 100, 5)

Функция `linspace` удобна еще и тем, что может быть использована для вычисления значений функций на заданном множестве точек:

In [ ]:
x = np.linspace(0, 2*np.pi, 10)
x

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [ ]:
y1 = np.sin(x)
y1

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [ ]:
y2 = np.cos(x)
y2

array([ 1.        ,  0.76604444,  0.17364818, -0.5       , -0.93969262,
       -0.93969262, -0.5       ,  0.17364818,  0.76604444,  1.        ])

### Вывод массивов на экран



Одномерные массивы в NumPy печатаются в виде строк:

In [ ]:
a = np.arange(10)    #  Одномерный массив
print(a)

Двумерные массивы печатаются в виде матриц:

In [ ]:
b = np.arange(1600).reshape(400, 4)    #  Двумерный массив
print(b)

[[   0    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 ...
 [1588 1589 1590 1591]
 [1592 1593 1594 1595]
 [1596 1597 1598 1599]]


Трехмерные массивы печатаются в виде списка матриц, которые разделены пустой строкой:

In [ ]:
c = np.arange(30).reshape(5, 2, 3)    #  Трехмерный массив
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]]




В случае, если массив очень большой (больше 1000 элементов), NumPy печатает только начало и конец массива, заменяя его центральную часть многоточием.

In [ ]:
print(np.arange(1001))

In [ ]:
print(np.arange(1000000))

In [ ]:
print(np.arange(1000000).reshape(1000,1000))

Если необходимо выводить весь массив целиком, то такое поведение печати можно изменить с помощью `set_printoptions`.

> np.set_printoptions(threshold=np.nan)

### Файловый ввод и вывод массивов



Двоичные файлы NumPy (.npy, .npz)

NumPy имеет два собственных формата файлов `.npy` - для хранения массивов без сжатия и `.npz` - для предварительного сжатия массивов. 

Если массивы, которые необходимо сохранить являются небольшими, то можно воспользоваться функцией `numpy.save()`. В самом простом случае, данная функция принимает всего два аргумента - имя файла в который будет сохранен массив и имя самого сохраняемого массива. 

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

In [ ]:
b = np.arange(16).reshape(4, 4)
b

In [ ]:

np.save('example_1', a)

После того как массив сохранен, его можно загрузить из файла с помощью функции `numpy.load()`, указав в виде строки имя необходимого файла или путь к нему

In [ ]:
import numpy as np

a = np.load('example_1.npy')
a

array([[ 2,  4,  3],
       [ 6,  8,  1],
       [10, 12,  6]])

Файлы `.npy` удобны для хранения одного массива, если в одном файле нужно сохранить несколько массивов, то необходимо воспользоваться функцией `numpy.savez()`, которая сохранит их в несжатом виде в файле NumPy с форматом `.npz`.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1, 1], [0, 0]])
c = np.array([[1], [2], [3]])

np.savez('example_2', a, b, c)

После сохранения массивов в файл `.npz` они могут быть загружены с помощью, уже знакомой нам функции `numpy.load()`. Однако, имена массивов теперь изменились с `a`, `b` и `c` на `arr_0`, `arr_1` и `arr_2` соответственно:

In [ ]:
ex_2 = np.load('example_2.npz')

In [ ]:
ex_2.files

In [ ]:
ex_2['arr_0']

array([1, 2, 3])

In [ ]:
ex_2['arr_1']

array([[1, 1],
       [0, 0]])

In [ ]:
ex_2['arr_2']

array([[1],
       [2],
       [3]])

Что бы вместе с массивами сохранялись их оригинальные имена, необходимо в функции `numpy.savez()` указывать их как ключи словарей Python:

In [ ]:
np.savez('example_2', a_=a, b=b, c=c)

In [ ]:
ex_2 = np.load('example_2.npz')

In [ ]:
ex_2.files

In [ ]:
ex_2['a_']

array([1, 2, 3])

В случае очень больших массивов можно воспользоваться функцией `numpy.savez_compressed()`.

In [ ]:
a = np.arange(100000)
a

In [ ]:
#  Файл example_3.npy занимает 400 кБ на диске:
np.save('example_3', a)

#  файл example_3.npynpz занимает всего 139 кБ на диске:
np.savez_compressed('example_3', a)